/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeancesRouteImport } from './routes/seances'
import { Route as ReserverRouteImport } from './routes/reserver'
import { Route as DecouvrirRouteImport } from './routes/decouvrir'
import { Route as IndexRouteImport } from './routes/index'

const SeancesRoute = SeancesRouteImport.update({
  id: '/seances',
  path: '/seances',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverRoute = ReserverRouteImport.update({
  id: '/reserver',
  path: '/reserver',
  getParentRoute: () => rootRouteImport,
} as any)
const DecouvrirRoute = DecouvrirRouteImport.update({
  id: '/decouvrir',
  path: '/decouvrir',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decouvrir': typeof DecouvrirRoute
  '/reserver': typeof ReserverRoute
  '/seances': typeof SeancesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decouvrir': typeof DecouvrirRoute
  '/reserver': typeof ReserverRoute
  '/seances': typeof SeancesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decouvrir': typeof DecouvrirRoute
  '/reserver': typeof ReserverRoute
  '/seances': typeof SeancesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decouvrir' | '/reserver' | '/seances'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decouvrir' | '/reserver' | '/seances'
  id: '__root__' | '/' | '/decouvrir' | '/reserver' | '/seances'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecouvrirRoute: typeof DecouvrirRoute
  ReserverRoute: typeof ReserverRoute
  SeancesRoute: typeof SeancesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seances': {
      id: '/seances'
      path: '/seances'
      fullPath: '/seances'
      preLoaderRoute: typeof SeancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver': {
      id: '/reserver'
      path: '/reserver'
      fullPath: '/reserver'
      preLoaderRoute: typeof ReserverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decouvrir': {
      id: '/decouvrir'
      path: '/decouvrir'
      fullPath: '/decouvrir'
      preLoaderRoute: typeof DecouvrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecouvrirRoute: DecouvrirRoute,
  ReserverRoute: ReserverRoute,
  SeancesRoute: SeancesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
